KotlinSprint-20-4
ConstantineBoitsov/KotlinSprint pull request #101
Opened 2024-05-19 20:17 UTC by ConstantineBoitsov

— attempt to make a list of lambdas

2024-05-19 20:22 UTC, ConstantineBoitsov commented
Код ещё неисправен, потому что я не смог понять, как с помощью map превратить строку в лямбду. Получилось просто добавить лямбду в список и вызвать её через it(), но создать список из этих лямбд map'ом – хоть убей, не понимаю.
По ТЗ лямбды должны выводить текст в консоль, тогда тип этого списка лямбд должен быть <() -> Unit>, но как вернуть этот тип из map? Подскажи, пожалуйста!

2024-05-20 08:35 UTC, ievetrovdev requested changes

2024-05-20 08:35 UTC, ievetrovdev commented on src/main/kotlin/lesson_20/lesson_20_task_4.kt
> +    val lambdify: (String) -> Unit = { it: String ->
Тут нехватке фигурных скобочек чтобы возвращать лямбду и в мае ее преобразовывать в unit
```

fun main() {

    val listOfString = listOf(
        "Blah-blah!",
        "Yo-yo!",
        "Meh-meh!",
        "Pee-pee!",
        "Bow-wow!",
    )

    val lambdify = { it: String -> {
        println("Нажат элемент «${it}»")}
    }

    val listOfLambda = listOfString.map {
        lambdify(it)
    }

    listOfLambda.forEachIndexed { index, action ->
        if ((index + 1) % 2 == 0) {
            action.invoke() // или просто action()
        }
    }
}
```

2024-05-21 06:13 UTC, ievetrovdev approved these changes

2024-05-26 10:56 UTC, ConstantineBoitsov commented on src/main/kotlin/lesson_20/lesson_20_task_4.kt
> +    val lambdify: (String) -> Unit = { it: String ->
Спасибо!

2024-05-26 10:56 UTC, merged