KotlinSprint-3-4 chess turn logger
ConstantineBoitsov/KotlinSprint pull request #14
Opened 2023-07-25 14:02 UTC by ConstantineBoitsov

Задание 3-4

2023-07-26 21:08 UTC, ievetrov requested changes

2023-07-26 21:08 UTC, ievetrov commented on src/main/kotlin/lesson_3/lesson_3_task_4.kt
> +    print("$fromX$fromY-$toX$toY;${++turnCounter}")
по условию формат модели данных состоит из 3 переменных. это может быть важной деталью при взаимодействии с сервером. предлагаю ограничить переменные до [откуда-куда;номер хода]

2023-07-28 16:10 UTC, ConstantineBoitsov commented
Ошибся в коммите, это 3-4)

2023-07-29 07:48 UTC, ievetrov approved these changes
ок!

2023-07-29 08:23 UTC, merged