KotlinSprint-4-4 trainings program
ConstantineBoitsov/KotlinSprint pull request #19
Opened 2023-08-01 17:36 UTC by ConstantineBoitsov

Задание 4-4
Не понял пункт задания «программа должна быть легко поддерживаема (чтобы можно было быстро добавить или убрать какие-то типы тренировок)». Мне нужно было внедрить массив?

2023-08-02 06:10 UTC, ievetrov commented
> Задание 4-4
> Не понял пункт задания «программа должна быть легко поддерживаема (чтобы можно было быстро добавить или убрать какие-то типы тренировок)». Мне нужно было внедрить массив?

в этом задании как раз нужно было сделать как в твоем варианте) мы можем легко удалить или добавить новое упражнение

2023-08-02 06:10 UTC, ievetrov requested changes

2023-08-02 06:10 UTC, ievetrov commented on src/main/kotlin/lesson_4/lesson_4_task_4.kt
> +        Упражнения для пресса:  ${dayOfTraining % 2 == 1}
все ок, только у тебя здесь много повторяющегося кода, может проверку четности дня вынести в отдельную функцию?

2023-08-02 10:31 UTC, ConstantineBoitsov commented
Сделал функцию для проверки чётности дня.

2023-08-03 04:53 UTC, ievetrov approved these changes

2023-08-03 05:33 UTC, merged