Lesson1 task2
ConstantineBoitsov/KotlinSprint pull request #2
Opened 2023-07-12 17:15 UTC by ConstantineBoitsov

Исправил многострочный текст на обычный для простоты вывода.

2023-07-12 20:51 UTC, ievetrov requested changes
Есть нарушения в git флоу, то есть в логике работы с коммитами и ветками.
Обрати внимание, сначала ты сделал задачу 1, запушил и все ок.

Затем ты создал новую ветку, но закоммитил в нее не только нужную задачу (2), но и файл, который не относится к этой задаче.

Нужно переключиться во 2 ветку, удалить файл с ненужной задачей, сделать коммит и переотправить ссылку на этот ПР в бот.
А чтобы такого не происходило обращай внимание что у тебя попадает в стейдж перед коммитом (где ты галками выбираешь какие файлы попадут в коммит)

2023-07-13 13:57 UTC, ConstantineBoitsov commented
Спасибо. 
Я правильно понял?

2023-07-13 14:00 UTC, ievetrov approved these changes
да, теперь все чисто) аппрув!

2023-07-13 16:36 UTC, merged

2023-07-14 08:05 UTC, ConstantineBoitsov commented
Подскажи, пожалуйста, что я сделал не так?
После удаления файла 1-1 из ветки 1-2 я сделал пулл, и файл первого задания удалился также из главной ветки.
Мне стоит повторить процедуру первого задания? Как вернуться к предыдущей версии проекта, я пока не разобрался. :)

2023-07-14 13:12 UTC, ievetrov reviewed
это пулл реквест к задаче 2, а в бот ты отправил ссылку к задаче 3)
по комменту отпишусь в ЛС