KotlinSprint-6-2 seconds counter
ConstantineBoitsov/KotlinSprint pull request #27
Opened 2023-08-06 16:01 UTC by ConstantineBoitsov

Задание 6-2

2023-08-07 08:56 UTC, ievetrov requested changes

2023-08-07 08:56 UTC, ievetrov commented on src/main/kotlin/lesson_6/lesson_6_task_2.kt
> +        1 -> print("Прошла $secondsToCount секунда, спасибо за ожидание!")
отлично, а давай чуть оптимизируем. чтобы финальное сообщение печаталось только 1 раз, а в условии изменялось только окончание (только слово секунда). так избавимся от дублирования кода

2023-08-08 15:30 UTC, ievetrov requested changes
довольно технично вышло)

2023-08-08 15:30 UTC, ievetrov commented on src/main/kotlin/lesson_6/lesson_6_task_2.kt
> +        1 -> {
отлично)
- фигурные скобки нужны для многострочного тела ветвления. здесь можно опустить и просто писать букву на строке со стрелкой

2023-08-11 13:51 UTC, ConstantineBoitsov commented
Запушилось два коммита, потому что первый куда-то потерялся, и пушить якобы было нечего. Добавил в код строчку с комментарием, чтобы можно было закоммитить ещё раз, запушил, и с новым коммитом вылез предыдущий утерянный. Иван, я ничего не поняль.

2023-08-12 15:41 UTC, ievetrov commented
> Запушилось два коммита, потому что первый куда-то потерялся, и пушить якобы было нечего. Добавил в код строчку с комментарием, чтобы можно было закоммитить ещё раз, запушил, и с новым коммитом вылез предыдущий утерянный. Иван, я ничего не поняль.

вероятнее всего первый коммит был сделан локально, а второй уже с отправкой на сервер. там при создании коммита есть просто commit, а есть commit & push

если сделан локально, то можно отдельно выбрать коммит из списка, ПКМ и запушить на сервер вручную

2023-08-12 15:42 UTC, ievetrov approved these changes

2023-08-13 08:43 UTC, merged