KotlinSprint-6-5 The Turing test before the registration
ConstantineBoitsov/KotlinSprint pull request #30
Opened 2023-08-11 14:43 UTC by ConstantineBoitsov

Задание 6-5

2023-08-12 15:54 UTC, ievetrov requested changes

2023-08-12 15:54 UTC, ievetrov commented on src/main/kotlin/lesson_6/lesson_6_task_5.kt
> +        exitProcess(0)
тут тоже лучше выходить через return

2023-08-12 15:54 UTC, ievetrov commented on src/main/kotlin/lesson_6/lesson_6_task_5.kt
> +    while (typedLogin != registeredLogin) {
предлагаю немного доработать. пусть программа запрашивает сразу и логин и пароль, затем проверяет их также. чтобы не было возможности скомпрометировать данные

2023-08-17 07:21 UTC, ievetrov requested changes

2023-08-17 07:21 UTC, ievetrov commented on src/main/kotlin/lesson_6/lesson_6_task_5.kt
> +    loop@ while (numberOfTries > 0) {
Старайся не использовать лейблы (loop в твоем случае).
Тут он вообще не нужен, но и в целом - метки затрудняют навигацию по коду, а необходимость их использования говорит о плохом проектировании метода.

2023-08-17 08:02 UTC, ConstantineBoitsov commented on src/main/kotlin/lesson_6/lesson_6_task_5.kt
> +    loop@ while (numberOfTries > 0) {
Спасибо. Нагуглил что-то не то...

2023-08-18 07:28 UTC, ievetrov approved these changes

2023-08-18 12:49 UTC, merged