KotlinSprint-7-2
ConstantineBoitsov/KotlinSprint pull request #32
Opened 2023-08-15 16:36 UTC by ConstantineBoitsov

— verification code checker

2023-08-16 04:34 UTC, ievetrov requested changes

2023-08-16 04:34 UTC, ievetrov commented on src/main/kotlin/lesson_7/lesson_7_task_2.kt
> +    while (typedCode != verificationCode) {
попробуй немного сократить количество кода, сделав все операции внутри цикла:
```
do {
...
} while(...)
```

2023-08-16 06:35 UTC, ConstantineBoitsov commented
Спасибо, не сразу признал преимущество do-while в некоторых ситуациях!

2023-08-17 04:40 UTC, ievetrov approved these changes

2023-08-17 08:04 UTC, merged