KotlinSprint-8-4
ConstantineBoitsov/KotlinSprint pull request #39
Opened 2023-08-22 17:08 UTC by ConstantineBoitsov

— changing one ingredient in the recipe

2023-08-22 17:15 UTC, ConstantineBoitsov commented
Я очень хотел сделать всё красиво, побольше кода завернуть в циклы, но вышло топорно. Прошу дать конструктивный разгром)

2023-08-25 14:38 UTC, ConstantineBoitsov commented
Я долго думал, но не понял, как сделать красиво, и сделал топорно. Прошу конструктивный разгром!

2023-08-26 07:39 UTC, ievetrov requested changes

2023-08-26 07:39 UTC, ievetrov commented on src/main/kotlin/lesson_8/lesson_8_task_4.kt
> +        print(
Реализация отличная, все логично - запрашиваем ингредиент пока не найдем имеющийся. Смущает только использование многострочного вывода, особенно, там, где не требуется)

Предлагаю тут сократить строки используя обычный принт

2023-08-26 07:39 UTC, ievetrov commented on src/main/kotlin/lesson_8/lesson_8_task_4.kt
> +    println(
а тут использовать символ переноса строки в принте

2023-08-26 07:39 UTC, ievetrov commented on src/main/kotlin/lesson_8/lesson_8_task_4.kt
> +        Ингредиенты весёлого порошка: ${theFunPowderRecipe.joinToString(", ", "", ".")}""".trimIndent()
И по ТЗ текст другой. В продакшене это крайне важно - соблюдать все детали задания

2023-08-26 07:39 UTC, ievetrov commented on src/main/kotlin/lesson_8/lesson_8_task_4.kt
> +    while (ingredientToSwap !in theFunPowderRecipe) {
здесь мне кажется лучше применить do while - чтобы один раз запрашивать ввод элемента с консоли

2023-08-28 14:13 UTC, ConstantineBoitsov commented
Спасибо, исправил всё, кроме последней правки. Прошу подсказать, можно ли в этот do-while засунуть сообщение о некорректном вводе, потому что совершенно не понимаю. Через while в закомменченном коде это получилось.

2023-08-29 07:45 UTC, ievetrov commented
> Спасибо, исправил всё, кроме последней правки. Прошу подсказать, можно ли в этот do-while засунуть сообщение о некорректном вводе, потому что совершенно не понимаю. Через while в закомменченном коде это получилось.

У меня получилось только с дополнительным `if`. В него поместил всю логику, когда элемент заменяется останавливаем программу. Решение не претендует на самое оптимальное и компактное, но кейс с одним reeadln для каждого действия решили)

   ```
 val theFunPowderRecipe = arrayOf("сироп вишнёвый", "смешное слово", "шоколадка", "две шутки", "загадка")

    println("Ингредиенты весёлого порошка: ${theFunPowderRecipe.joinToString(", ", "", ".")}")

    var ingredientToSwap: String

    do {
        print("Какой ингредиент вы хотели бы заменить? ")
        ingredientToSwap = readln()

        if (ingredientToSwap in theFunPowderRecipe) {
            print("На что его заменить? ")
            theFunPowderRecipe[theFunPowderRecipe.indexOf(ingredientToSwap)] = readln()
            println("Готово!\nВы сохранили следующий список: ${theFunPowderRecipe.joinToString(", ", "", ".")}")
            return
        } else {
            println("Такого ингредиента нет, попробуйте ещё раз.")
        }

    } while (ingredientToSwap !in theFunPowderRecipe)
```

2023-08-29 07:47 UTC, ievetrov requested changes
в идеале я бы вынес проверку `ingredientToSwap !in theFunPowderRecipe` в отдельную функцию, чтобы не дублировать код (и в if тоже бы применял этот метод, чтобы проверки были одинаковые)

2023-08-30 10:19 UTC, ConstantineBoitsov commented
Спасибо! Я почему-то думал, что проверять то же условие внутри цикла – это плохой тон. Но я сделал бы совершенно идентично)

2023-08-30 10:28 UTC, ConstantineBoitsov commented on src/main/kotlin/lesson_8/lesson_8_task_4.kt
> +            )
А не является ли плохим тоном деление длинной строки кода на более короткие?

2023-08-31 07:14 UTC, ievetrov commented
> Спасибо! Я почему-то думал, что проверять то же условие внутри цикла – это плохой тон. Но я сделал бы совершенно идентично)

это точно не плохой тон. это уже пересечение целей задачи и вкусовщина, просто иногда можно сделать оптимальнее. здесь, как я уже сказал на мой взгляд не самое оптимальное решение, как минимум дополнительных функций для проверок можно было бы добавить. но в целом челлендж был оставить один ридлайн)

2023-08-31 07:17 UTC, ievetrov commented on src/main/kotlin/lesson_8/lesson_8_task_4.kt
> +            )
вообще наша цель писать понятный читаемый код. а длинные строки ухудшают восприятие. принты в продакшене практически не используются и лично мне многоэтажные принты не очень заходят, здесь бы я список поместил в отдельную переменную. но когда не обойтись без длинной строки, то так лучше да

2023-08-31 07:17 UTC, ievetrov approved these changes

2023-08-31 22:30 UTC, merged