KotlinSprint-1-4 the space task 2.0
ConstantineBoitsov/KotlinSprint pull request #4
Opened 2023-07-16 16:14 UTC by ConstantineBoitsov

2023-07-17 09:45 UTC, ievetrov requested changes

2023-07-17 09:45 UTC, ievetrov commented on src/main/kotlin/lesson_1/lesson_1_task_4.kt
> +fun main () {
по решению все великолепно!
небольшой нюанс на этой строке - в сигнатуре функции перед круглыми скобками пробел не нужен

2023-07-17 14:19 UTC, ConstantineBoitsov commented
Отучился ставить пробел после main!

2023-07-18 13:59 UTC, ievetrov approved these changes
ок)

2023-07-18 14:16 UTC, merged