KotlinSprint-9-2 – adding new ingredients to the list
ConstantineBoitsov/KotlinSprint pull request #42
Opened 2023-08-30 15:24 UTC by ConstantineBoitsov

2023-08-31 07:32 UTC, ievetrov requested changes

2023-08-31 07:32 UTC, ievetrov commented on src/main/kotlin/lesson_9/lesson_9_task_2.kt
> +    if ((desireToAdd == "да") or (desireToAdd == "Да")) {
а пользователь еще может ввести капсом)
метод equals имеет параметр, который вообще игнорирует регистр при сравнении

2023-08-31 22:37 UTC, ConstantineBoitsov commented on src/main/kotlin/lesson_9/lesson_9_task_2.kt
> +    if ((desireToAdd == "да") or (desireToAdd == "Да")) {
Спасибо, круто!

2023-09-01 11:20 UTC, ievetrov approved these changes
огонь!

2023-09-02 12:07 UTC, merged