KotlinSprint-10-2 — check if login or password are too short
ConstantineBoitsov/KotlinSprint pull request #47
Opened 2023-09-06 16:38 UTC by ConstantineBoitsov

2023-09-07 09:36 UTC, ievetrov requested changes

2023-09-07 09:36 UTC, ievetrov commented on src/main/kotlin/lesson_10/lesson_10_task_2.kt
> +fun isValidLength(login: String, password: String): Boolean =
по неймингу) такое название можете показаться подходящим для условия while, да. но все таки это даже не extension функция, а просто отдельно живущий метод. поэтому тут по прежнему не отступаем от правила названий методов в инфинитиве. поэтому больше подойдет что-то вроде validateLength()

2023-09-09 08:43 UTC, ConstantineBoitsov commented
Спасибо, буду внимательнее!

2023-09-09 10:24 UTC, ievetrov approved these changes
ок!

2023-09-09 10:25 UTC, merged