KotlinSprint-1-5 the space task 3.0
ConstantineBoitsov/KotlinSprint pull request #5
Opened 2023-07-16 17:09 UTC by ConstantineBoitsov

😵😵😵

2023-07-17 10:04 UTC, ievetrov requested changes

2023-07-17 10:04 UTC, ievetrov commented on src/main/kotlin/lesson_1/lesson_1_task_5.kt
> +    print("Время, проведённое в космосе: ${"%02d".format(hours)}:${"%02d".format(remainedMinutes)}:" +
хорошо! а попробуй объединить в один вызов через String.format()

2023-07-17 14:29 UTC, ConstantineBoitsov commented
Готово! Вывел строку через String.format().

2023-07-18 13:59 UTC, ievetrov approved these changes
все четко!

2023-07-18 14:17 UTC, merged