KotlinSprint-11-2 — working on user info
ConstantineBoitsov/KotlinSprint pull request #52
Opened 2023-09-22 12:32 UTC by ConstantineBoitsov

Делаю пуш с тяжёлыми мыслями, что неправильно понял задание...

2023-09-23 06:24 UTC, ievetrov requested changes

2023-09-23 06:24 UTC, ievetrov commented on src/main/kotlin/lesson_11/lesson_11_task_2.kt
> +    fun printUserData(userNumber: Int, user: SuperUser) {
сюда не обязательно передавать `user`, можем брать данные сразу из класса

2023-09-23 06:24 UTC, ievetrov commented on src/main/kotlin/lesson_11/lesson_11_task_2.kt
> +    fun setBio(superUser: SuperUser) {
сюда тоже не обязательно)

2023-09-26 07:00 UTC, ConstantineBoitsov commented
А ведь и вправду, спасибо!

2023-09-27 05:16 UTC, ievetrov approved these changes

2023-09-28 21:09 UTC, merged