KotlinSprint-11-3 — voice chat with thematic rooms
ConstantineBoitsov/KotlinSprint pull request #53
Opened 2023-09-22 16:49 UTC by ConstantineBoitsov

Мои извилины заскрежетали от такого творческого задания.....

2023-09-23 08:52 UTC, ievetrov requested changes

2023-09-23 08:52 UTC, ievetrov commented on src/main/kotlin/lesson_11/lesson_11_task_3.kt
> +    enum class UserStatus(val status: String) {
лучше не хранить `enum` внутри класса, давай его вынесем отсюда)

2023-09-23 08:52 UTC, ievetrov commented on src/main/kotlin/lesson_11/lesson_11_task_3.kt
> +    val status: String,
давай сюда передавать `UserStatus`, а не строку

2023-09-26 11:04 UTC, ConstantineBoitsov commented
Спасибо, исправил. Только в статусе участника комнаты теперь будет константа TALKS, а не "разговаривает", как было в тз.

2023-09-27 05:30 UTC, ievetrov commented
> Спасибо, исправил. Только в статусе участника комнаты теперь будет константа TALKS, а не "разговаривает", как было в тз.

можно `разговаривает` достать из RoomMember таким образом: `status.status`

2023-09-27 05:31 UTC, ievetrov approved these changes

2023-09-28 21:09 UTC, merged