KotlinSprint-11-5 — I don't get it, help me
ConstantineBoitsov/KotlinSprint pull request #55
Opened 2023-10-09 12:39 UTC by ConstantineBoitsov

Иван, прошу помочь. Вылез из мотивационной ямы и вернулся к обучению, но тут же очутился в тупике. :)
Кажется, у меня проблемы с логикой проектирования, а оттуда проблемы с видимостью внутри (или изнутри) companion object. 
Чтобы присваивать пользователям id при регистрации, я веду их учёт в поле usersTotal класса Forum. Я начитался в интернете всякого и решил фабричный шаблон реализовать через companion object.
Собственно, я прошу объяснить мне, не полез ли я в ненужные дебри с ним, потому что у меня не получается решить проблемы с видимостью, а внутри самого объекта-компаньона сделал всего 1 метод из заданных.
(код не дописан и не посему компилируется)

2023-10-10 06:12 UTC, ievetrov commented
> Иван, прошу помочь. Вылез из мотивационной ямы и вернулся к обучению, но тут же очутился в тупике. :)
> Кажется, у меня проблемы с логикой проектирования, а оттуда проблемы с видимостью внутри (или изнутри) companion object.
> Чтобы присваивать пользователям id при регистрации, я веду их учёт в поле usersTotal класса Forum. Я начитался в интернете всякого и решил фабричный шаблон реализовать через companion object.
> Собственно, я прошу объяснить мне, не полез ли я в ненужные дебри с ним, потому что у меня не получается решить проблемы с видимостью, а внутри самого объекта-компаньона сделал всего 1 метод из заданных.
> (код не дописан и посему не компилируется)

давай пока не будем усложнять и использовать `companion object`) в фабрике он обычно используется чтобы получать текущий экземпляр класса без создания самого класса. это позволяет хранить и контролировать актуальный объект внутри нашего companion в случае когда он используется из многих мест кода)

в твоем случае ты можешь функции создания юзера и сообщения сделать внутри класса `Forum`, а далее из main вызывать их просто через созданный экземпляр класса Forum)
```
val actualForum = Forum()
val user1 = actualForum.createNewUser(login = "CoolGuy", password = "assword", email = "mymail@mail.ru")
```

в остальном все ок, только я бы посоветовал еще добавить список внутри Forum для истории сообщений

2023-10-10 06:13 UTC, ievetrov requested changes

2023-10-10 06:13 UTC, ievetrov commented on src/main/kotlin/lesson_11/lesson_11_task_5.kt
> +//    public var usersTotal: Int = 0,
никакие параметры нам сюда передавать не нужно)

2023-10-15 19:14 UTC, ConstantineBoitsov commented
Спасибо, про объекты-компаньоны понял.
Пришлось переделать кое-что, так как условие задания поменялось, пока я над ним думал. Всё получилось, но я не сообразил, как при выводе списка сообщений найти автора поста именно по его id, а не по его номеру в списке юзеров. Просто у меня id члена форума – это его номер в списке всех членов форума, но +1, чтобы счёт начинался с 1.

2023-10-16 06:27 UTC, ievetrov commented
> Спасибо, про объекты-компаньоны понял. Пришлось переделать кое-что, так как условие задания поменялось, пока я над ним думал. Всё получилось, но я не сообразил, как при выводе списка сообщений найти автора поста именно по его id, а не по его номеру в списке юзеров. Просто у меня id члена форума – это его номер в списке всех членов форума, но +1, чтобы счёт начинался с 1.

правильно было бы сделать таким образом:
```
fun printThread() {
       messagesMutableList.forEach { message ->
            println("${usersMutableList.firstOrNull { it.userId == message.authorId }?.userName}: ${message.message}")
        }
    }
```

мы должны просто в списке юзеров найти автора сообщения по айди и достать его

2023-10-16 06:29 UTC, ievetrov requested changes

2023-10-16 06:29 UTC, ievetrov commented on src/main/kotlin/lesson_11/lesson_11_task_5.kt
> +        val newForumUser = ForumUser(userId = ++usersTotal, userName = name)
инкремент не обязательно делать, принято начинать нумерацию айдишников с 0

2023-10-16 06:29 UTC, ievetrov commented on src/main/kotlin/lesson_11/lesson_11_task_5.kt
> +    fun getUserId(user: ForumUser): Int {
этот метод кажется не обязательным, так как из места вызова мы можем сделать просто `user.userId`) можно было бы переделать этот метод для возврата самого пользователя по айдишнику

2023-10-16 12:19 UTC, ConstantineBoitsov commented
Спасибо, поработал над ошибками. Делал задание про создание экземпляров объектов, а в процессе узнал про лямбда-выражения и функции-предикаты, ха.

2023-10-17 06:18 UTC, ievetrov commented
> Спасибо, поработал над ошибками. Делал задание про создание экземпляров объектов, а в процессе узнал про лямбда-выражения и функции-предикаты, ха.

пятые задания всегда немного сложнее остальных))

2023-10-17 06:19 UTC, ievetrov requested changes

2023-10-17 06:19 UTC, ievetrov commented on src/main/kotlin/lesson_11/lesson_11_task_5.kt
> +//            message: ForumMessage ->
все супер, только давай не оставлять закомментированные куски кода в итоговом варианте)

2023-10-17 07:40 UTC, ConstantineBoitsov commented on src/main/kotlin/lesson_11/lesson_11_task_5.kt
> +//            message: ForumMessage ->
Упс... 🤦‍♂️

2023-10-18 03:49 UTC, ievetrov approved these changes

2023-10-18 06:59 UTC, merged