KotlinSprint-2-1 average grade
ConstantineBoitsov/KotlinSprint pull request #6
Opened 2023-07-22 12:26 UTC by ConstantineBoitsov

Задание 2-1

2023-07-23 11:55 UTC, ievetrov requested changes

2023-07-23 11:55 UTC, ievetrov commented on src/main/kotlin/lesson_2/lesson_2_task_1.kt
> +    var grades = listOf<Int>(3, 4, 3, 5)
а чем обусловлена изменяемая переменная? мы ее никак не перезаписываем потом

2023-07-23 11:55 UTC, ievetrov commented on src/main/kotlin/lesson_2/lesson_2_task_1.kt
> +    grades.forEach {sumOfGrades += it}
можно посчитать сумму, используя экстеншн sum()

2023-07-23 15:06 UTC, ConstantineBoitsov commented
Всё исправил, спасибо.

2023-07-24 10:35 UTC, ievetrov approved these changes
все отлично!

2023-07-24 18:14 UTC, merged