KotlinSprint-13-4
ConstantineBoitsov/KotlinSprint pull request #65
Opened 2024-01-08 19:47 UTC by ConstantineBoitsov

— contacts can be added to the phonebook and be printed then

2024-01-08 19:52 UTC, ConstantineBoitsov commented
Иван, серьёзно выпал из жизни и напрочь забыл почти всё, что умел. Помимо недочётов по актуальной теме, очень прошу с повышенной строгостью погонять меня по базовым вещам, с которыми я напортачил. Это помогло бы мне морально. :)

2024-01-10 06:41 UTC, ievetrovdev commented on src/main/kotlin/lesson_13/lesson_13_task_4.kt
> +            if (currentPhoneNumber == null) {
В целом, все хорошо. Я бы только тут чуть оптимизировал:
```Kotlin
  if (currentPhoneNumber == null) {
      println("\nНекорректный номер телефона. Попробуйте ещё раз.\n")
      break
  }
```

Тогда `while (true)` - чтобы в одном месте currentPhoneNumber проверять

2024-01-10 06:41 UTC, ievetrovdev requested changes
См. коммент

2024-01-11 09:37 UTC, ConstantineBoitsov commented
Спасибо, оптимизировал. Попутно исправил ошибку, что добавление в список было вне цикла создания контакта и потому добавляло контакт даже некорректный.

2024-01-11 10:40 UTC, ievetrovdev approved these changes

2024-01-11 11:09 UTC, merged