KotlinSprint-13-5
ConstantineBoitsov/KotlinSprint pull request #66
Opened 2024-01-08 20:35 UTC by ConstantineBoitsov

— string to long format with the exception

2024-01-10 06:45 UTC, ievetrovdev requested changes

2024-01-10 06:45 UTC, ievetrovdev commented on src/main/kotlin/lesson_13/lesson_13_task_5.kt
> +        println("NumberFormatException")
В целом корректно, так как ты отлавливаешь только NumberFormatException, но имя можно получить и из самого объекта ошибки: `e::class.simpleName`

2024-01-11 10:35 UTC, ConstantineBoitsov commented
Спасибо, теперь выводится имя ошибки, полученное из класса.

2024-01-11 11:06 UTC, ievetrovdev approved these changes

2024-01-11 11:09 UTC, merged