KotlinSprint-14-1 — ships hierarchy
ConstantineBoitsov/KotlinSprint pull request #67
Opened 2024-01-20 23:22 UTC by ConstantineBoitsov

2024-01-22 07:26 UTC, ievetrovdev requested changes

2024-01-22 07:26 UTC, ievetrovdev commented on src/main/kotlin/lesson_14/lesson_14_task_1.kt
> +) : LinerShip(speed, carryingCapacity, maxPassengers) {
пустое тело класса можно не делать, то есть - фигурные скобки не нужны

2024-01-22 07:26 UTC, ievetrovdev commented on src/main/kotlin/lesson_14/lesson_14_task_1.kt
> +) : LinerShip(speed, carryingCapacity, maxPassengers, iceBreaking = true) {
тут тоже скобки не нужны

2024-01-22 07:29 UTC, ievetrovdev requested changes
Технически все идеально, давай немного по стилистике поправим. Смотри комменты

2024-01-22 07:29 UTC, ievetrovdev commented on src/main/kotlin/lesson_14/lesson_14_task_1.kt
> +    val linerShip = LinerShip(40, 100, 100)
Когда в аргументах метода или конструктора много однотипных данных легко спутать, например скорость и максимальное количество пассажиров. Давай добавим имена аргументов

2024-01-23 10:17 UTC, ConstantineBoitsov commented
Спасибо, сделаль.

2024-01-24 22:59 UTC, ievetrov approved these changes

2024-01-25 10:52 UTC, merged