KotlinSprint-14-3
ConstantineBoitsov/KotlinSprint pull request #69
Opened 2024-02-01 16:40 UTC by ConstantineBoitsov

— sums of perimeters and areas of black and white figures

2024-02-03 09:46 UTC, ievetrovdev requested changes
Круто!

А крутость твоего решения, что все расчеты производятся в рамках одного цикла (forEach). Еще мог быть соблазн использовать filter{} для каждого цвета, но тогда циклов было бы больше. Есть маленькая правка

ps:
И вот тебе еще вариант решения при помощи foldRight{}, просто для расширения кругозора )):

```Kotlin
    val (blackFigurePerimeterSum, whiteFigureAreaSum) = differentFiguresList
        .foldRight(0.0 to 0.0) { figure, acc ->
            Pair(
                if (figure.color == "black") acc.first + figure.calculatePerimeter() else acc.first,
                if (figure.color == "white") acc.second + figure.calculateArea() else acc.second
            )
        }
```

2024-02-03 09:46 UTC, ievetrovdev commented on src/main/kotlin/lesson_14/lesson_14_task_3.kt
> +        else whiteFigureAreaSum += it.calculateArea()
Сейчас этот код работает корректно, но если добавить еще один цвет выше, все сломается.
Новый цвет будет считаться белым. Нужно более строгое условие

2024-02-04 17:27 UTC, ConstantineBoitsov commented
Благодарю!
Решил создать enum с цветами, а также поломал голову над fold и reduce в списках. 😃

2024-02-05 13:29 UTC, ievetrovdev approved these changes
Идеально!

2024-02-05 13:34 UTC, merged