KotlinSprint-14-5
ConstantineBoitsov/KotlinSprint pull request #71
Opened 2024-02-21 10:27 UTC by ConstantineBoitsov

— problems

2024-02-21 12:59 UTC, ievetrovdev requested changes

2024-02-21 12:59 UTC, ievetrovdev commented on src/main/kotlin/lesson_14/lesson_14_task_5.kt
> +            Message(messageId = currentMessageId++, authorName = author, messageText = text)
Давай возвращать из методов addMessage() и addThreadMessage() создаваемые сообщения.
Тогда можно воспользоваться возвращенным messageId и не делать манипуляций с `theGreatChat.currentMessageId`

2024-02-21 12:59 UTC, ievetrovdev commented on src/main/kotlin/lesson_14/lesson_14_task_5.kt
> +    val messageMutableList = mutableListOf<Message>()
можно не подчеркивать в названии, что данный список мутабельный. Достаточно messageList или messages

2024-02-21 12:59 UTC, ievetrovdev commented on src/main/kotlin/lesson_14/lesson_14_task_5.kt
> +    val groupedMessages = theGreatChat.messageMutableList.groupBy { it.messageId }
группировку и вывод нужно делать внутри printChat()

2024-02-21 12:59 UTC, ievetrovdev commented on src/main/kotlin/lesson_14/lesson_14_task_5.kt
> +
Extension-функция groupBy принимает в качестве параметра лямбду, которая возвращает критерий для каждого объекта, по которому производится группировка.

В задаче обозначено:
> Используй groupBy() для группировки сообщений по parentMessageId, если сообщение является экземпляром ChildMessage, или по id если это обычное сообщение.

То есть, нам нужен if:

```Kotlin
val threadMap: Map<Int, List<Message>> = messages.groupBy {
    if (it is ChildMessage)
        it.parentMessageId
    else
        it.id
}
```

Шпаргалка:

<img width="800" alt="Screenshot 2024-02-21 at 15 58 39" src="https://github.com/ConstantineBoitsov/KotlinSprint/assets/153023186/ed9f5f98-3c0e-4ac0-888e-a08016b54279">

2024-03-01 19:57 UTC, ConstantineBoitsov commented
Спасибо, было интересно!

2024-03-03 13:26 UTC, ievetrovdev approved these changes
🥇

2024-03-13 11:25 UTC, merged