KotlinSprint-15-4
ConstantineBoitsov/KotlinSprint pull request #75
Opened 2024-03-20 20:47 UTC by ConstantineBoitsov

— internet music shop

2024-03-21 06:05 UTC, ievetrovdev requested changes

2024-03-21 06:05 UTC, ievetrovdev commented on src/main/kotlin/lesson_15/lesson_15_task_4.kt
> +class Components(
класс - это каркас для будущей сущности, поэтому во множественном числе называть их некорректно

2024-03-21 14:52 UTC, ConstantineBoitsov commented
Упс...

2024-03-22 06:28 UTC, ievetrovdev approved these changes

2024-03-23 20:22 UTC, merged