KotlinSprint-16-5
ConstantineBoitsov/KotlinSprint pull request #82
Opened 2024-03-31 01:17 UTC by ConstantineBoitsov

— fight game where one of players dies

2024-03-31 01:21 UTC, ConstantineBoitsov commented
Хотел сделать поинтереснее – с выбором атаки/лечения случайным образом, чтобы сражение было в цикле и шло до смерти одного из игроков. Не смог придумать, как в функцию атаки передавать объект-оппонента.

2024-03-31 06:58 UTC, ievetrovdev requested changes

2024-03-31 06:58 UTC, ievetrovdev commented on src/main/kotlin/lesson_16/lesson_16_task_5.kt
> +
по коду очень много пустых лишних строчек, попробуй сделать автоформатирование кода, обычно он исправляет это)

2024-03-31 06:58 UTC, ievetrovdev commented on src/main/kotlin/lesson_16/lesson_16_task_5.kt
> +//    while (!player1.isDead() or !player2.isDead()) {
лучше не оставлять закомментированные куски кода в итоговом варианте

2024-03-31 06:58 UTC, ievetrovdev commented on src/main/kotlin/lesson_16/lesson_16_task_5.kt
> +    fun isDead() : Boolean {
эту функцию можно сделать приватной

2024-03-31 19:51 UTC, ConstantineBoitsov commented
Спасибо, всё подкрутил.

2024-04-01 06:43 UTC, ievetrovdev approved these changes

2024-04-01 09:33 UTC, merged