KotlinSprint-19-4
ConstantineBoitsov/KotlinSprint pull request #96
Opened 2024-05-13 20:11 UTC by ConstantineBoitsov

— battle tank with different ammo types

2024-05-15 05:39 UTC, ievetrovdev requested changes
Давай немного сократим

2024-05-15 05:39 UTC, ievetrovdev commented on src/main/kotlin/lesson_19/lesson_19_task_4.kt
> +    abstract fun getAmmunitionColor(): String
Если поместить внутри getAmmunitionColor() when, можно сократить код на несколько строк

2024-05-16 19:57 UTC, ievetrovdev requested changes

2024-05-16 19:57 UTC, ievetrovdev commented on src/main/kotlin/lesson_19/lesson_19_task_4.kt
> +    NO_AMMO(0)
В ТЗ указано только 3 типа снарядов

2024-05-16 19:57 UTC, ievetrovdev commented on src/main/kotlin/lesson_19/lesson_19_task_4.kt
> +    private var ammunitionType = AmmunitionType.NO_AMMO
Все хорошо, но в данном случае стоит допустить null значение, и воспользоваться им как флагом отсутствия снаряда.

2024-05-17 07:59 UTC, ConstantineBoitsov commented
Спасибо, классная возможность вспомнить про null'ы!

2024-05-17 11:41 UTC, ievetrovdev approved these changes
Вот теперь все отлично!

2024-05-19 17:27 UTC, merged