KotlinSprint-19-5
ConstantineBoitsov/KotlinSprint pull request #97
Opened 2024-05-13 23:58 UTC by ConstantineBoitsov

— card index

2024-05-15 05:49 UTC, ievetrovdev requested changes

2024-05-15 05:49 UTC, ievetrovdev commented on src/main/kotlin/lesson_19/lesson_19_task_5.kt
> +            if (!typedGender.equals(other = "муж", ignoreCase = true)
эта конструкция условия дублируется несколько раз. Может попробуем вынести в функцию.
И в целом, попробуем сократить количество while`ов

2024-05-19 16:25 UTC, ConstantineBoitsov commented
Отказался от регулярных выражений для разделения имени и пола в строке ввода (потому что не осилил), но убрал нагромождение while'ов!

2024-05-20 06:47 UTC, ievetrovdev requested changes

2024-05-20 06:47 UTC, ievetrovdev commented on src/main/kotlin/lesson_19/lesson_19_task_5.kt
> +    do {
Лучше использовать цикл while. do while - это на самом деле редкая конструкция, она усложняет код, и желательно прибегать к ней в редких случаях когда первая итерация цикла должна всегда выполняться.

2024-05-20 06:47 UTC, ievetrovdev commented on src/main/kotlin/lesson_19/lesson_19_task_5.kt
> +        println("${i.name}, пол ${i.gender.sex}")
Формат вывода лучше вынести в метод класса Person.

2024-05-26 13:22 UTC, ievetrovdev approved these changes
Все верно, отличная работа!

2024-05-26 13:32 UTC, merged